### ISSUE TITLE
Can `curl` be added?

### ISSUE THREAD

**Issue by agneevX** [hurlenko/aria2-ariang-docker#12]
Hello,

I use a script that uses curl to send a notification to Telegram whenever a download has completed. This requires `curl` to be installed, so can it be added to the Dockerfile?

**Comment by hurlenko** [comment]
Hi, the image has `wget` instead. Have you tried that?

**Comment by agneevX** [comment]
Yes, it does not support `POST` since its mainly used for downloading data.

**Comment by agneevX** [comment]
Any update @hurlenko? I can submit a PR, if you're up for it.

**Comment by hurlenko** [comment]
Hello @agneevX, 
Sorry for the late response, didn't have much time to answer. Latest docker version (tags 1.2.4/latest onwards) has curl installed

**Comment by agneevX** [comment]
Thanks @hurlenko!
