### ISSUE TITLE
after reboot lose all settings

### ISSUE THREAD

**Issue by Stephen988** [hurlenko/aria2-ariang-docker#4]
Hi guys, after installed docker compose on my raspberry pi 4 I have test ariang and work well for download files, but after reboot it lose all customs settings, I also save in Aria2 Status > Save session.

**Comment by hurlenko** [comment]
Can you paste the contents of your docker-compose.yaml file? All the settings are saved in the `/aria2/conf` directory inside of the container. You need to create a volume and map this directory to the volume.

**Comment by Stephen988** [comment]
> Can you paste the contents of your docker-compose.yaml file? All the settings are saved in the `/aria2/conf` directory inside of the container. You need to create a volume and map this directory to the volume.

---
version: "2.4"
services:
  ariang:
    image: hurlenko/aria2-ariang
    ports:
      - 443:8080
    volumes:
      - /srv/dev-disk-by-label-Data-WD/NAS/Download:/aria2/data
      - /srv/dev-disk-by-KINGSTON_SA400S37120/appdata/ariang:/aria2/conf
    environment:
      - PUID=1001
      - PGID=100
      - DOMAIN=0.0.0.0:8080
      - ARIA2RPCPORT=443
    restart: unless-stopped

**Comment by hurlenko** [comment]
Okay, now I see what's your issue. Any changes in webui will reset after reboot, you should edit aria2.conf file for persistant change. AriaNg cannot edit the file directly as it runs in the browser which does not allow file access by design and aria2 rpc has no functionality to update the `aria2.conf` file.

XUJINKAI/aria2-with-webui#3
MichaIng/DietPi#1575
ziahamza/webui-aria2#60
mayswind/AriaNg-Native#17

**Comment by Stephen988** [comment]
> Okay, now I see what's your issue. Any changes in webui will reset after reboot, you should edit aria2.conf file for persistant change. AriaNg cannot edit the file directly as it runs in the browser which does not allow file access by design and aria2 rpc has no functionality to update the `aria2.conf` file.
> 
> [XUJINKAI/aria2-with-webui#3](https://github.com/XUJINKAI/aria2-with-webui/issues/3)
> [MichaIng/DietPi#1575](https://github.com/MichaIng/DietPi/issues/1575)
> [ziahamza/webui-aria2#60](https://github.com/ziahamza/webui-aria2/issues/60)
> [mayswind/AriaNg-Native#17](https://github.com/mayswind/AriaNg-Native/issues/17)

Thanks a lot @hurlenko, only another questions, can I change port 443 for open it? and about ip 192.168.x.x:443/jsonrpc I have tried to open it but don't work, I have also think about open this ip with duckdns but seems not work

**Comment by hurlenko** [comment]
You can change the port using the `ARIA2RPCPORT` environment variable. If you want to expose AriaNg to the Internet you need an external IP address. You can search how to do it on the Internet. 192.168.x.x is an internal  IP address an can be accessed only from local network.

**Comment by Stephen988** [comment]
> You can change the port using the `ARIA2RPCPORT` environment variable. If you want to expose AriaNg to the Internet you need an external IP address. You can search how to do it on the Internet. 192.168.x.x is an internal IP address an can be accessed only from local network.

Hi @hurlenko yes I mean:
- 192.168.x.x:443 open webgui, but :443/jsonrpc not, what do it?
- ok now with duckdns address and external port work perfectly.
- about domain 0.0.0.0:8080 what I can do with it?

**Comment by hurlenko** [comment]
I don't seem to understand your issue. I've just tried running `docker run --name ariang -it -e ARIA2RPCPORT=443 -p 443:8080 hurlenko/aria2-ariang` and it works fine on `localhost:443`. If you want to configure https you can use some web server like NGINX, truffle, caddy etc

**Comment by Stephen988** [comment]
> I don't seem to understand your issue. I've just tried running `docker run --name ariang -it -e ARIA2RPCPORT=443 -p 443:8080 hurlenko/aria2-ariang` and it works fine on `localhost:443`. If you want to configure https you can use some web server like NGINX, truffle, caddy etc

Now I can use in local network 192.168.x.x:443 and duckdnsdomain:extport for outside access and all works fine.
I ask what to do /jsonrpc, is for remote access? and about 0.0.0.0 I can replace it with? or I don't need it for simple use like this on raspberry.
After all you can close my issue if you want, now the container in local network work fine, thanks for support.

**Comment by hurlenko** [comment]
`/jsonrpc` is the aria2 rpc endpoint. It is used by AriaNG for rpc calls. Basically there are two applications running inside the container, aria2 download manager and caddy web server that serves static files for AriaNG. When running inside your browser AriaNG makes calls to the `/jsonrpc`, [caddy redirects all calls to this endpoint to aria2 rpc](https://github.com/hurlenko/aria2-ariang-docker/blob/a583ba76216e33aae122b10a93dc19bc5ec241b8/Caddyfile#L3).

As for the `0.0.0.0:8080` default domain, which is controlled by the `DOMAIN` environment variable - you may want to use it if you don't run the container behind a web server like NGINX and you want to bind your server to a specifi domain

**Comment by Stephen988** [comment]
I can remove from env if I don't use domain 0.0.0.0?

**Comment by hurlenko** [comment]
Yes

**Comment by Stephen988** [comment]
thanks a lot for your support!

**Comment by candrapersada** [comment]
how to copy aria2 from AriraNg settings, paste it into aria2.conf or create a new aria2.conf
