### ISSUE TITLE
Caddy Error. Please help!

### ISSUE THREAD

**Issue by capriciousduck** [hurlenko/aria2-ariang-docker#5]
`Changing rpc request port to 8000
Running as user 0:0

01/26 13:45:46 [NOTICE] IPv4 RPC: listening on TCP port 6800
[ERROR] first argument must be a subcommand; see 'caddy help'`

**Comment by hurlenko** [comment]
Please give more details about how you run the container (eg exact docker run command or docker-compose.yaml example)

**Comment by capriciousduck** [comment]
This is the docker command.

`docker run -d --restart unless-stopped     --name ariang     -p 8000:8080     -v /mnt/DS1:/aria2/data/DS1     -v /mnt/DS2:/aria2/DS2     -v ariang_config:/aria2/conf     -e PUID=0     -e PGID=0     -e RPC_SECRET=myrpcsecret hurlenko/aria2-ariang`

**Comment by hurlenko** [comment]
It works perfectly fine for me. What system are you running it on (os, architecture etc)?

**Comment by capriciousduck** [comment]
I am running it on my laptop. Mine is lenovo laptop (running ubuntu)

**Comment by Stephen988** [comment]
I have same issue:
```
02/25 22:39:07 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.
02/25 22:39:07 [NOTICE] IPv4 RPC: listening on TCP port 6800
[ERROR] first argument must be a subcommand; see 'caddy help'
02/25 22:39:17 [NOTICE] Serialized session to '/aria2/conf/aria2.session' successfully.
```
until a few days ago it has always worked for months, now blank page "ERR_CONNECTION_REFUSED"

my system run on raspberry pi 4, raspbian os with docker 5:20.10.3 debian buster

**Comment by chneau** [comment]
Hello,
This command not working for me:
```bash
docker run --rm -it hurlenko/aria2-ariang:1.2.1
```
Output:
```
Changing rpc request port to 8080

02/27 20:44:41 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.

02/27 20:44:41 [NOTICE] IPv4 RPC: listening on TCP port 6800
[ERROR] first argument must be a subcommand; see 'caddy help'

02/27 20:44:51 [NOTICE] Serialized session to '/aria2/conf/aria2.session' successfully.
```

Compared to previous version:
```bash
docker run --rm -it hurlenko/aria2-ariang:1.1.7
```

Output:
```
Changing rpc request port to 8080

02/27 20:48:18 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.

02/27 20:48:18 [NOTICE] IPv4 RPC: listening on TCP port 6800

02/27 20:48:28 [NOTICE] Serialized session to '/aria2/conf/aria2.session' successfully.
```

No Caddy issue.

Here is some context:

```bash
uname -a
# Linux oo 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a 
# No LSB modules are available.
# Distributor ID: Ubuntu
# Description:    Ubuntu 20.04.2 LTS
# Release:        20.04
# Codename:       focal

docker version
# Client: Docker Engine - Community
#  Version:           20.10.4
#  API version:       1.41
#  Go version:        go1.13.15
#  Git commit:        d3cb89e
#  Built:             Thu Feb 25 07:05:27 2021
#  OS/Arch:           linux/amd64
#  Context:           default
#  Experimental:      true
# 
# Server: Docker Engine - Community
#  Engine:
#   Version:          20.10.4
#   API version:      1.41 (minimum version 1.12)
#   Go version:       go1.13.15
#   Git commit:       363e9a8
#   Built:            Thu Feb 25 07:03:23 2021
#   OS/Arch:          linux/amd64
#   Experimental:     false
#  containerd:
#   Version:          1.4.3
#   GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
#  runc:
#   Version:          1.0.0-rc92
#   GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
#  docker-init:
#   Version:          0.19.0
#   GitCommit:        de40ad0
```

It might be coming from there:
https://github.com/hurlenko/aria2-ariang-docker/blob/a583ba76216e33aae122b10a93dc19bc5ec241b8/Dockerfile#L24

The version of caddy is not the same between the versions 1.1.7 and 1.2.1.

I can test that by:

```bash
docker run --rm -it --entrypoint caddy hurlenko/aria2-ariang:1.1.7 --help
docker run --rm -it --entrypoint caddy hurlenko/aria2-ariang:1.2.1 help
```

Since the two versions are different:
- To fix that one could update the command line used to start caddy to support caddy v2 as well as the Caddyfile (maybe?) https://caddyserver.com/docs/v2-upgrade#command-line https://github.com/hurlenko/aria2-ariang-docker/blob/412857ec620a00c1a5b037e605004ca201f072d5/start.sh#L33
- or pin alpine version to 3.12 https://pkgs.org/download/caddy https://github.com/hurlenko/aria2-ariang-docker/blob/412857ec620a00c1a5b037e605004ca201f072d5/Dockerfile#L1

**Comment by Stephen988** [comment]
Hi @chneau can you tell me how to solve?
```
I have this log message on portainer:
Changing rpc request port to 443
Running as user 1001:100
02/27 21:43:29 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.
02/27 21:43:29 [NOTICE] IPv4 RPC: listening on TCP port 6800
[ERROR] first argument must be a subcommand; see 'caddy help'
02/27 21:43:39 [NOTICE] Serialized session to '/aria2/conf/aria2.session' successfully.
```

**Comment by chneau** [comment]
Hi @Stephen988,

I would suggest you just use `hurlenko/aria2-ariang:1.1.7` docker image.
That's what I'm doing at the moment and I've got no issues.

**Comment by Stephen988** [comment]
> Hi @Stephen988,
> 
> I would suggest you just use `hurlenko/aria2-ariang:1.1.7` docker image.
> That's what I'm doing at the moment and I've got no issues.

Thanks a lot! now ariang works again, hope in fix for latest version.
I don't know why but I have used any new version up to 1.3.5 for a long time without issue.
But anyway thanks for the trick!

**Comment by hurlenko** [comment]
@chneau Thanks for your detailed investigation! Indeed the problem happened because of caddy update to cli v2 in alpine:3.13. Not pinning the base docker image version was a very bad idea 😅. I've updated the Dockerfile, rebuilt and updated the last AriaNg release. Seems to be working fine now.

@capriciousduck @Stephen988 This should be fixed now. Please remove local image and redownload:

```docker image rm hurlenko/aria2-ariang:latest```

**Comment by Stephen988** [comment]
> @chneau Thanks for your detailed investigation! Indeed the problem happened because of caddy update to cli v2 in alpine:3.13. Not pinning the base docker image version was a very bad idea 😅. I've updated the Dockerfile, rebuilt and updated the last AriaNg release. Seems to be working fine now.
> 
> @capriciousduck @Stephen988 This should be fixed now. Please remove local image and redownload:
> 
> `docker image rm hurlenko/aria2-ariang:latest`

Thanks, now work well!

**Comment by hurlenko** [comment]
I think I can close the issue now. Feel free to open another issue if you find any problems..
