### ISSUE TITLE
[enhanchement] HTTP Basic Auth + autocompile RPC secret 

### ISSUE THREAD

**Issue by FrancYescO** [hurlenko/aria2-ariang-docker#7]
Can we add some envs for the the possibility to set a basicauth for the UI and if set precompile the RPC secret on the UI (https://github.com/wahyd4/aria2-ariang-docker/blob/master/aria2c.sh#L4-L5)?

in this way we can have a ready to go and password protected container that can be directly exposed on a single port

**Comment by hurlenko** [comment]
Hello @FrancYescO, 
I know it's been a while but this is now supported since version 1.2.4 (tags 1.2.4/latest)
