### ISSUE TITLE
Disable Caddy telemetry

### ISSUE THREAD

**Issue by titeishon** [hurlenko/aria2-ariang-docker#8]
Caddy introduced opt-out telemetry recently, it pings telemetry.caddyserver.com constantly. 

Should be opt-in or at least have an environment variable turning it off.

Thanks!

**Comment by Stunkymonkey** [comment]
by using `Alpine-3.13` -> `caddy-2.3.0` would be used, which does not have any telemetry enabled by default. the Version 2 is a complete rewrite.

**Comment by hurlenko** [comment]
Hello @titeishon, latest docker image version is using caddy v2, so the issue should be fixed now
